### ISSUE TITLE
PHP 7.4 - Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`  - line  475

### ISSUE THREAD

**Issue by mbrinson** [jamesckemp/WordPress-Settings-Framework#39]
This can be fixed by changing line 475 from:

$subfield['value'] = ( $blank ) ? "" : isset( $args['value'][ $row ][ $subfield['id'] ] ) ? $args['value'][ $row ][ $subfield['id'] ] : "";

To

$subfield['value'] = (( $blank ) ? "" : isset( $args['value'][ $row ][ $subfield['id'] ] )) ? $args['value'][ $row ][ $subfield['id'] ] : "";

**Comment by jamesckemp** [comment]
Fixed!
