### ISSUE TITLE
Duplicate admin notices

### ISSUE THREAD

**Issue by raideus** [jamesckemp/WordPress-Settings-Framework#9]
Whenever I save settings, I see duplicates of the admin notice messages (ie "Settings saved." displays twice on the page).  I deactivated all other plugins and switched to a default WP theme to rule out any possible issues with other plugins/themes.  

I was able to resolve this by removing the "admin_notices" hook on line 38.  

Any idea why this is happening?  Is the call to settings_errors() necessary in the framework?  It seems like WordPress is already displaying them by default.

**Comment by jamesckemp** [comment]
Seems like if you add the settings page under the "Settings" tab, the settings notices are duplicated. I've implement a fix for this into the latest branch.

**Comment by richrd** [comment]
I actually have experienced this too, probably because my settings are under the "Settings" tab, like you said.

**Comment by jamesckemp** [comment]
I'm just in the process of implement a "tab" system for the settings display, with that I'll add a fix for duplicate messages!

**Comment by richrd** [comment]
Wow, tabs would be super nice! :+1:

**Comment by jamesckemp** [comment]
All done! Check it out and let me know of issues (be sure to check the demo plugin and the example settings, too)
